[package]
name = "sqlite"
version = "0.1.0"
edition = "2021"
workspace = ".."
publish = false

[dependencies]
rusql-alchemy  = { workspace = trueÂ , features = ["sqlite"] }
sqlx.workspace = true
tokio = { workspace = true, features = ["full"] }
